## NUMPY (NUMERICAL PYTHON)

In [1]:
import numpy as np

In [2]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [3]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [4]:
np.array([[2,3,4],[4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [5]:
l=[[1,2,3,4],[2,3,4,5]]

In [6]:
l[0][0]

1

In [7]:
l[0][1]

2

In [8]:
a=np.array([3,4,5,6],ndmin=3)

In [9]:
a

array([[[3, 4, 5, 6]]])

In [10]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr.ndim

2

In [13]:
np.random.randint(1,10,(4,4))

array([[1, 2, 2, 5],
       [4, 4, 7, 1],
       [5, 4, 6, 7],
       [3, 5, 8, 8]])

In [14]:
np.random.randint(1,10,(4,4,2))

array([[[4, 4],
        [7, 7],
        [2, 5],
        [6, 7]],

       [[5, 8],
        [3, 1],
        [9, 7],
        [2, 5]],

       [[1, 6],
        [4, 6],
        [7, 3],
        [7, 6]],

       [[5, 1],
        [8, 1],
        [9, 5],
        [1, 5]]])

In [1]:
### 13th August ###

In [2]:
import numpy as np

In [9]:
l=[1,2,3,4,5,6]

In [10]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [29]:
l1=[4,5,6,7,"sudh",34.565,True]

In [30]:
 np.array(l1)

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [14]:
np.array([[[1,2,3],[4,5,6],[7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
a1=np.array(l1)

In [17]:
a2=np.array([[1,2,3],[4,5,6]])

In [18]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [32]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [20]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

## Number of dimensions

In [22]:
a1.ndim

1

In [23]:
a2.ndim

2

In [24]:
a3.ndim

3

In [33]:
a1.size

7

In [26]:
a2.size

6

In [27]:
a3.size

9

In [34]:
a1.shape

(7,)

In [37]:
a2.shape

(2, 3)

In [38]:
a3.shape

(1, 3, 3)

In [73]:
np.random.randint(2,50)

18

In [74]:
np.random.randint(2,50,(3,4))

array([[15, 22, 47, 39],
       [ 7, 18, 37, 31],
       [24,  3, 20, 40]])

In [42]:
np.random.randn(4,4)

array([[-2.04914532,  1.56639682,  0.52896215, -0.21347609],
       [-0.48331111, -1.54295581,  0.38476535,  0.78696828],
       [-1.66966686, -0.81080927, -0.80390122, -1.10062247],
       [-0.70321836,  0.00974618,  0.14104772, -0.40407739]])

In [43]:
a4=np.random.randn(4,4)

In [44]:
a4

array([[ 2.99388318, -1.0630061 ,  1.36789159,  0.37607502],
       [-0.71592218, -0.5986328 ,  1.04143213, -0.02228817],
       [-0.01736771, -1.10411501, -0.09124417, -1.43029505],
       [-0.07225939, -0.18477699,  0.21682751,  0.91168645]])

In [45]:
a4=np.random.randn(2,8)

## n=normal distribution

In [46]:
a4

array([[-1.5033825 , -0.27733549,  0.53080685,  1.56947736,  2.54552763,
        -0.39540307, -0.49500065,  1.18829619],
       [ 0.25513053, -2.17241149,  1.57109625, -0.30087288,  0.56255454,
         0.93855909,  1.54387514,  0.30475939]])

In [47]:
a4=np.random.randn(8,2)

In [48]:
a4

array([[ 0.22019708,  0.27952113],
       [ 1.12802802,  0.57007831],
       [ 0.66236301,  0.67031144],
       [-0.67244056, -1.41129578],
       [-1.54544885,  0.97201386],
       [ 1.9309643 ,  0.30742504],
       [-1.16469618,  0.22103129],
       [-1.23345107,  0.41898814]])

In [49]:
a4=np.random.randn(16,1)

In [50]:
a4

array([[ 0.41166966],
       [-0.16968687],
       [ 2.37261483],
       [ 0.35309686],
       [-0.11364447],
       [-1.3631453 ],
       [ 0.97269123],
       [-0.22839278],
       [-0.81975159],
       [ 0.07869983],
       [ 0.62869887],
       [ 1.07817182],
       [ 0.97393147],
       [-1.90811967],
       [ 1.42109975],
       [-0.82255388]])

## RESHAPE 

In [53]:
a4.reshape(2,8)

array([[ 0.41166966, -0.16968687,  2.37261483,  0.35309686, -0.11364447,
        -1.3631453 ,  0.97269123, -0.22839278],
       [-0.81975159,  0.07869983,  0.62869887,  1.07817182,  0.97393147,
        -1.90811967,  1.42109975, -0.82255388]])

In [54]:
a4.reshape(8,2)

array([[ 0.41166966, -0.16968687],
       [ 2.37261483,  0.35309686],
       [-0.11364447, -1.3631453 ],
       [ 0.97269123, -0.22839278],
       [-0.81975159,  0.07869983],
       [ 0.62869887,  1.07817182],
       [ 0.97393147, -1.90811967],
       [ 1.42109975, -0.82255388]])

In [55]:
a4.reshape(16,1)

array([[ 0.41166966],
       [-0.16968687],
       [ 2.37261483],
       [ 0.35309686],
       [-0.11364447],
       [-1.3631453 ],
       [ 0.97269123],
       [-0.22839278],
       [-0.81975159],
       [ 0.07869983],
       [ 0.62869887],
       [ 1.07817182],
       [ 0.97393147],
       [-1.90811967],
       [ 1.42109975],
       [-0.82255388]])

In [56]:
a4.reshape(16,1)

array([[ 0.41166966],
       [-0.16968687],
       [ 2.37261483],
       [ 0.35309686],
       [-0.11364447],
       [-1.3631453 ],
       [ 0.97269123],
       [-0.22839278],
       [-0.81975159],
       [ 0.07869983],
       [ 0.62869887],
       [ 1.07817182],
       [ 0.97393147],
       [-1.90811967],
       [ 1.42109975],
       [-0.82255388]])

In [57]:
a4.reshape(2,-1)

array([[ 0.41166966, -0.16968687,  2.37261483,  0.35309686, -0.11364447,
        -1.3631453 ,  0.97269123, -0.22839278],
       [-0.81975159,  0.07869983,  0.62869887,  1.07817182,  0.97393147,
        -1.90811967,  1.42109975, -0.82255388]])

In [59]:
a4.reshape(2,-16652)

array([[ 0.41166966, -0.16968687,  2.37261483,  0.35309686, -0.11364447,
        -1.3631453 ,  0.97269123, -0.22839278],
       [-0.81975159,  0.07869983,  0.62869887,  1.07817182,  0.97393147,
        -1.90811967,  1.42109975, -0.82255388]])

In [60]:
a4.reshape(2,2,4)

array([[[ 0.41166966, -0.16968687,  2.37261483,  0.35309686],
        [-0.11364447, -1.3631453 ,  0.97269123, -0.22839278]],

       [[-0.81975159,  0.07869983,  0.62869887,  1.07817182],
        [ 0.97393147, -1.90811967,  1.42109975, -0.82255388]]])

In [61]:
a4.reshape(1,1,1,1,2,2,4)

array([[[[[[[ 0.41166966, -0.16968687,  2.37261483,  0.35309686],
            [-0.11364447, -1.3631453 ,  0.97269123, -0.22839278]],

           [[-0.81975159,  0.07869983,  0.62869887,  1.07817182],
            [ 0.97393147, -1.90811967,  1.42109975, -0.82255388]]]]]]])

In [62]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [63]:
a1[0]

'4'

In [64]:
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

In [65]:
a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

In [66]:
a1[::-1]

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [67]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
a2[0]

array([1, 2, 3])

##  slicing (Extract columns)

In [79]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

## Give me a record whose value is more than 50 

In [77]:
a5=np.random.randint(2,50,(6,5))

In [78]:
a5

array([[36, 41, 24, 39, 40],
       [27,  3, 19, 33,  2],
       [30,  9, 17, 15, 16],
       [35, 20, 34,  7, 42],
       [45, 13, 43, 13, 22],
       [41, 49, 40, 25, 21]])

In [81]:
a5[a5>40]

array([41, 42, 45, 43, 41, 49])

In [82]:
a5

array([[36, 41, 24, 39, 40],
       [27,  3, 19, 33,  2],
       [30,  9, 17, 15, 16],
       [35, 20, 34,  7, 42],
       [45, 13, 43, 13, 22],
       [41, 49, 40, 25, 21]])

### Repalce number in a particular column

In [83]:
a5[0,1]=100

In [84]:
a5

array([[ 36, 100,  24,  39,  40],
       [ 27,   3,  19,  33,   2],
       [ 30,   9,  17,  15,  16],
       [ 35,  20,  34,   7,  42],
       [ 45,  13,  43,  13,  22],
       [ 41,  49,  40,  25,  21]])

In [107]:
a6=np.random.randint(0,3,(3,3))

In [108]:
a6

array([[0, 1, 1],
       [2, 1, 0],
       [2, 0, 2]])

In [109]:
a7=np.random.randint(0,3,(3,3))

In [110]:
a7

array([[0, 0, 0],
       [1, 0, 2],
       [2, 1, 0]])

## Multiplication of two array

In [111]:
a6*a7

array([[0, 0, 0],
       [2, 0, 0],
       [4, 0, 0]])

## Matrix multipication

In [112]:
a6@a7

array([[3, 1, 2],
       [1, 0, 2],
       [4, 2, 0]])

In [113]:
a6+100

array([[100, 101, 101],
       [102, 101, 100],
       [102, 100, 102]])

In [114]:
a6/0

C:\Users\ANULIP~1\AppData\Local\Temp/ipykernel_16184/1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\ANULIP~1\AppData\Local\Temp/ipykernel_16184/1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[nan, inf, inf],
       [inf, inf, nan],
       [inf, nan, inf]])

## Power operation

In [115]:
a6**2

array([[0, 1, 1],
       [4, 1, 0],
       [4, 0, 4]], dtype=int32)

In [118]:
a8=np.zeros((4,4))

In [119]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [121]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Transpose

In [122]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [123]:
## with out transpose

In [124]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [125]:
a6.T

array([[0, 2, 2],
       [1, 1, 0],
       [1, 0, 2]])

In [126]:
a6

array([[0, 1, 1],
       [2, 1, 0],
       [2, 0, 2]])

In [127]:
a5

array([[ 36, 100,  24,  39,  40],
       [ 27,   3,  19,  33,   2],
       [ 30,   9,  17,  15,  16],
       [ 35,  20,  34,   7,  42],
       [ 45,  13,  43,  13,  22],
       [ 41,  49,  40,  25,  21]])

## Square root

In [131]:
np.sqrt(a5)

array([[ 6.        , 10.        ,  4.89897949,  6.244998  ,  6.32455532],
       [ 5.19615242,  1.73205081,  4.35889894,  5.74456265,  1.41421356],
       [ 5.47722558,  3.        ,  4.12310563,  3.87298335,  4.        ],
       [ 5.91607978,  4.47213595,  5.83095189,  2.64575131,  6.4807407 ],
       [ 6.70820393,  3.60555128,  6.55743852,  3.60555128,  4.69041576],
       [ 6.40312424,  7.        ,  6.32455532,  5.        ,  4.58257569]])

## Exponinent

In [132]:
np.exp(a5)

array([[4.31123155e+15, 2.68811714e+43, 2.64891221e+10, 8.65934004e+16,
        2.35385267e+17],
       [5.32048241e+11, 2.00855369e+01, 1.78482301e+08, 2.14643580e+14,
        7.38905610e+00],
       [1.06864746e+13, 8.10308393e+03, 2.41549528e+07, 3.26901737e+06,
        8.88611052e+06],
       [1.58601345e+15, 4.85165195e+08, 5.83461743e+14, 1.09663316e+03,
        1.73927494e+18],
       [3.49342711e+19, 4.42413392e+05, 4.72783947e+18, 4.42413392e+05,
        3.58491285e+09],
       [6.39843494e+17, 1.90734657e+21, 2.35385267e+17, 7.20048993e+10,
        1.31881573e+09]])

## Range Function

In [133]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Identical matrix

( diagonal matrix is 1 or determinant is 1) 

In [4]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])